
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/fetch_fsm 

module fetch_fsm(clk, rst_n, de_p, eip_4, ic_hit, r_V_de, int, ic_exp,
     dc_exp, de_br_stall, ld_eip, f_ld_buf, f_curr_st, f_next_st,
     f_address_sel, f_nextstate_01_11);
  input clk, rst_n, de_p, eip_4, ic_hit, r_V_de, int, ic_exp, dc_exp,
       de_br_stall;
  input [1:0] ld_eip;
  output [1:0] f_ld_buf;
  output [2:0] f_curr_st, f_next_st;
  output f_address_sel, f_nextstate_01_11;
  wire clk, rst_n, de_p, eip_4, ic_hit, r_V_de, int, ic_exp, dc_exp,
       de_br_stall;
  wire [1:0] ld_eip;
  wire [1:0] f_ld_buf;
  wire [2:0] f_curr_st, f_next_st;
  wire f_address_sel, f_nextstate_01_11;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_53, n_55, n_56, n_57, n_58, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_68, n_72;
  dff$ \f_curr_st_reg[1] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_72),
       .q (f_curr_st[1]), .qbar (UNCONNECTED));
  and2$ g4840(.in0 (f_next_st[1]), .in1 (n_60), .out (n_72));
  dff$ f_address_sel_reg(.r (rst_n), .s (1'b1), .clk (clk), .d (n_68),
       .q (f_address_sel), .qbar (UNCONNECTED0));
  dff$ \f_curr_st_reg[0] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_62),
       .q (f_curr_st[0]), .qbar (UNCONNECTED1));
  dff$ \f_curr_st_reg[2] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_64),
       .q (f_curr_st[2]), .qbar (UNCONNECTED2));
  nor2$ g4847(.in0 (n_58), .in1 (n_26), .out (n_68));
  nor2$ g4850(.in0 (n_66), .in1 (n_65), .out (f_next_st[0]));
  nand3$ g4843(.in0 (n_56), .in1 (n_61), .in2 (n_53), .out
       (f_next_st[1]));
  nor2$ g4849(.in0 (n_63), .in1 (n_11), .out (n_64));
  and4$ g4846(.in0 (n_57), .in1 (n_61), .in2 (n_46), .in3 (n_60), .out
       (n_62));
  inv1$ g4856(.in (n_63), .out (f_next_st[2]));
  nor2$ g4848(.in0 (n_55), .in1 (n_35), .out (n_58));
  nand3$ g4861(.in0 (n_57), .in1 (n_31), .in2 (n_24), .out (n_66));
  and3$ g4851(.in0 (n_49), .in1 (n_23), .in2 (n_50), .out (n_56));
  nand4$ g4857(.in0 (n_44), .in1 (n_29), .in2 (n_43), .in3 (n_25), .out
       (n_63));
  nor2$ g4863(.in0 (n_48), .in1 (n_21), .out (n_57));
  nor2$ g4852(.in0 (n_47), .in1 (n_40), .out (n_55));
  nand3$ g4870(.in0 (n_16), .in1 (n_53), .in2 (n_51), .out
       (f_ld_buf[1]));
  nand3$ g4853(.in0 (n_42), .in1 (n_38), .in2 (n_51), .out
       (f_ld_buf[0]));
  mux2$ g4860(.s0 (ic_hit), .in0 (n_34), .in1 (n_14), .outb (n_50));
  inv1$ g4880(.in (n_48), .out (n_49));
  inv1$ g4854(.in (n_65), .out (n_61));
  nor2$ g4858(.in0 (n_45), .in1 (n_30), .out (n_47));
  nor3$ g4881(.in0 (ld_eip[0]), .in1 (ld_eip[1]), .in2 (n_22), .out
       (n_48));
  nor2$ g4866(.in0 (n_32), .in1 (n_39), .out (n_46));
  nor2$ g4855(.in0 (n_37), .in1 (n_45), .out (n_65));
  nor2$ g4869(.in0 (n_19), .in1 (n_41), .out (n_44));
  nand3$ g4862(.in0 (n_28), .in1 (n_36), .in2 (r_V_de), .out (n_43));
  nand2$ g4865(.in0 (ic_hit), .in1 (n_33), .out (n_42));
  or2$ g4875(.in0 (n_40), .in1 (n_39), .out (n_41));
  nand4$ g4876(.in0 (r_V_de), .in1 (de_p), .in2 (ic_hit), .in3 (n_27),
       .out (n_38));
  nand3$ g4859(.in0 (n_36), .in1 (n_35), .in2 (r_V_de), .out (n_37));
  inv1$ g4877(.in (n_33), .out (n_34));
  inv1$ g4882(.in (n_31), .out (n_32));
  nand2$ g4864(.in0 (n_36), .in1 (r_V_de), .out (n_30));
  nand4$ g4867(.in0 (de_p), .in1 (r_V_de), .in2 (n_28), .in3 (n_27),
       .out (n_29));
  nand3$ g4868(.in0 (n_25), .in1 (n_60), .in2 (n_24), .out (n_26));
  nand4$ g4872(.in0 (r_V_de), .in1 (ic_hit), .in2 (n_0), .in3 (n_13),
       .out (n_53));
  nand2$ g4878(.in0 (n_20), .in1 (n_18), .out (n_33));
  nand2$ g4879(.in0 (n_6), .in1 (n_27), .out (n_23));
  nand2$ g4883(.in0 (n_5), .in1 (n_17), .out (n_31));
  inv1$ g4885(.in (n_40), .out (n_22));
  nor2$ g4871(.in0 (ic_hit), .in1 (n_20), .out (n_21));
  nor2$ g4874(.in0 (ic_hit), .in1 (n_18), .out (n_19));
  nor2$ g4873(.in0 (de_p), .in1 (n_12), .out (n_36));
  inv1$ g4884(.in (n_17), .out (n_51));
  nand2$ g4890(.in0 (ic_hit), .in1 (n_15), .out (n_16));
  nor2$ g4891(.in0 (n_10), .in1 (f_curr_st[2]), .out (n_40));
  nand2$ g4895(.in0 (n_28), .in1 (n_15), .out (n_25));
  nand2$ g4886(.in0 (n_9), .in1 (f_curr_st[2]), .out (n_20));
  nor2$ g4887(.in0 (n_14), .in1 (f_curr_st[0]), .out (n_17));
  and2$ g4888(.in0 (n_4), .in1 (f_curr_st[2]), .out (n_27));
  inv1$ g4893(.in (n_12), .out (n_13));
  inv1$ g4892(.in (n_39), .out (n_24));
  inv1$ g4894(.in (n_60), .out (n_11));
  nor3$ g4896(.in0 (f_curr_st[0]), .in1 (n_7), .in2 (f_curr_st[1]),
       .out (n_39));
  nor3$ g4897(.in0 (n_2), .in1 (n_28), .in2 (1'b0), .out (n_45));
  nand3$ g4899(.in0 (f_curr_st[0]), .in1 (n_8), .in2 (f_curr_st[2]),
       .out (n_12));
  or2$ g4889(.in0 (n_3), .in1 (f_curr_st[2]), .out (n_18));
  inv1$ g4901(.in (n_9), .out (n_10));
  inv1$ g4907(.in (n_14), .out (n_15));
  nand2$ g4908(.in0 (n_8), .in1 (n_7), .out (n_14));
  nand3$ g4898(.in0 (de_p), .in1 (ic_hit), .in2 (r_V_de), .out (n_6));
  nor4$ g4900(.in0 (dc_exp), .in1 (ic_exp), .in2 (int), .in3
       (de_br_stall), .out (n_60));
  nor2$ g4902(.in0 (n_8), .in1 (f_curr_st[0]), .out (n_9));
  nand2$ g4903(.in0 (n_1), .in1 (ic_hit), .out (n_5));
  inv1$ g4904(.in (n_3), .out (n_4));
  nor2$ g4906(.in0 (ld_eip[1]), .in1 (ld_eip[0]), .out (n_35));
  nand2$ g4905(.in0 (f_curr_st[0]), .in1 (f_curr_st[1]), .out (n_3));
  inv1$ g4911(.in (r_V_de), .out (n_2));
  inv1$ g4912(.in (eip_4), .out (n_1));
  inv1$ g4914(.in (ic_hit), .out (n_28));
  inv1$ g4913(.in (de_p), .out (n_0));
  inv1$ g4910(.in (f_curr_st[1]), .out (n_8));
  inv1$ g4909(.in (f_curr_st[2]), .out (n_7));
  nor2$ g2(.in0 (n_63), .in1 (n_66), .out (f_nextstate_01_11));
endmodule

