
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/writeback_loads_gen 

module writeback_loads_gen(V_wb, CF_expected, cond_wr_CF, CF_flag,
     cxchg_op, ZF_new, ld_mem, ld_seg, ld_mm, ld_reg1, ld_reg2,
     ld_reg3, ld_reg1_strb, ld_reg2_strb, ld_reg3_strb,
     v_wb_ld_reg1_strb, v_wb_ld_reg2_strb, v_wb_ld_reg3_strb,
     v_wb_ld_reg1, v_wb_ld_reg2, v_wb_ld_reg3, v_wb_ld_mm, v_wb_ld_seg,
     v_wb_ld_mem);
  input V_wb, CF_expected, cond_wr_CF, CF_flag, cxchg_op, ZF_new,
       ld_mem, ld_seg, ld_mm, ld_reg1, ld_reg2, ld_reg3;
  input [3:0] ld_reg1_strb, ld_reg2_strb, ld_reg3_strb;
  output [3:0] v_wb_ld_reg1_strb, v_wb_ld_reg2_strb, v_wb_ld_reg3_strb;
  output v_wb_ld_reg1, v_wb_ld_reg2, v_wb_ld_reg3, v_wb_ld_mm,
       v_wb_ld_seg, v_wb_ld_mem;
  wire V_wb, CF_expected, cond_wr_CF, CF_flag, cxchg_op, ZF_new,
       ld_mem, ld_seg, ld_mm, ld_reg1, ld_reg2, ld_reg3;
  wire [3:0] ld_reg1_strb, ld_reg2_strb, ld_reg3_strb;
  wire [3:0] v_wb_ld_reg1_strb, v_wb_ld_reg2_strb, v_wb_ld_reg3_strb;
  wire v_wb_ld_reg1, v_wb_ld_reg2, v_wb_ld_reg3, v_wb_ld_mm,
       v_wb_ld_seg, v_wb_ld_mem;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_13;
  wire n_17, n_18, n_19;
  and2$ g480(.in0 (n_19), .in1 (n_1), .out (v_wb_ld_reg2));
  and3$ g482(.in0 (V_wb), .in1 (n_17), .in2 (ld_reg2), .out (n_19));
  and3$ g483(.in0 (V_wb), .in1 (n_0), .in2 (ld_mem), .out
       (v_wb_ld_mem));
  or2$ g484(.in0 (CF_expected), .in1 (CF_flag), .out (n_18));
  nand2$ g486(.in0 (cxchg_op), .in1 (ZF_new), .out (n_17));
  and2$ g490(.in0 (V_wb), .in1 (ld_reg3), .out (v_wb_ld_reg2));
  nand2$ g491(.in0 (CF_expected), .in1 (CF_flag), .out (n_13));
  and2$ g494(.in0 (V_wb), .in1 (ld_reg3_strb[3]), .out
       (v_wb_ld_reg3_strb[3]));
  and2$ g495(.in0 (V_wb), .in1 (ld_reg3_strb[2]), .out
       (v_wb_ld_reg3_strb[2]));
  and2$ g496(.in0 (V_wb), .in1 (ld_reg3_strb[1]), .out
       (v_wb_ld_reg3_strb[1]));
  and2$ g497(.in0 (V_wb), .in1 (ld_reg3_strb[0]), .out
       (v_wb_ld_reg3_strb[0]));
  and2$ g501(.in0 (V_wb), .in1 (ld_mm), .out (v_wb_ld_mm));
  and2$ g502(.in0 (V_wb), .in1 (ld_seg), .out (v_wb_ld_seg));
  inv1$ g504(.in (ZF_new), .out (n_6));
  nand3$ g523(.in0 (n_13), .in1 (n_18), .in2 (cond_wr_CF), .out (n_5));
  nand2$ g485_dup528(.in0 (n_6), .in1 (cxchg_op), .out (n_4));
  nand2$ g533(.in0 (n_6), .in1 (cxchg_op), .out (n_3));
  nand3$ g481_dup538(.in0 (n_13), .in1 (n_18), .in2 (cond_wr_CF), .out
       (n_2));
  nand3$ g481_dup_dup539(.in0 (n_13), .in1 (n_18), .in2 (cond_wr_CF),
       .out (n_1));
  nand2$ g518_dup540(.in0 (n_6), .in1 (cxchg_op), .out (n_0));
  and4$ g2(.in0 (V_wb), .in1 (ld_reg1_strb[3]), .in2 (n_5), .in3 (n_3),
       .out (v_wb_ld_reg1_strb[3]));
  and4$ g541(.in0 (V_wb), .in1 (ld_reg1_strb[2]), .in2 (n_1), .in3
       (n_0), .out (v_wb_ld_reg1_strb[2]));
  and4$ g542(.in0 (V_wb), .in1 (ld_reg2_strb[2]), .in2 (n_5), .in3
       (n_3), .out (v_wb_ld_reg2_strb[2]));
  and4$ g543(.in0 (V_wb), .in1 (ld_reg2_strb[1]), .in2 (n_1), .in3
       (n_0), .out (v_wb_ld_reg2_strb[1]));
  and4$ g544(.in0 (V_wb), .in1 (ld_reg1_strb[1]), .in2 (n_2), .in3
       (n_4), .out (v_wb_ld_reg1_strb[1]));
  and4$ g545(.in0 (V_wb), .in1 (ld_reg2_strb[0]), .in2 (n_1), .in3
       (n_0), .out (v_wb_ld_reg2_strb[0]));
  and4$ g546(.in0 (V_wb), .in1 (ld_reg1_strb[0]), .in2 (n_2), .in3
       (n_4), .out (v_wb_ld_reg1_strb[0]));
  and4$ g547(.in0 (V_wb), .in1 (ld_reg1), .in2 (n_5), .in3 (n_3), .out
       (v_wb_ld_reg1));
  and4$ g548(.in0 (V_wb), .in1 (ld_reg2_strb[3]), .in2 (n_2), .in3
       (n_4), .out (v_wb_ld_reg2_strb[3]));
endmodule

