
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dc_hit_checker 

module dc_hit_checker(phy_tag, ts_tag, ts_valid, ts_dirty, tlb_pcd,
     ren, wen, v_mem_read, dc_miss_ack, access2_reg, access2_combo,
     dc_rd_exp, io_ack, io_access, mem_rd_ready, mem_wr_done,
     mem_rd_busy, mem_wr_busy, dc_miss, dc_evict, dc_hit, dc_rd_hit,
     dc_wr_hit);
  input [5:0] phy_tag, ts_tag;
  input ts_valid, ts_dirty, tlb_pcd, ren, wen, v_mem_read, dc_miss_ack,
       access2_reg, access2_combo, dc_rd_exp, io_ack, io_access;
  output mem_rd_ready, mem_wr_done, mem_rd_busy, mem_wr_busy, dc_miss,
       dc_evict, dc_hit, dc_rd_hit, dc_wr_hit;
  wire [5:0] phy_tag, ts_tag;
  wire ts_valid, ts_dirty, tlb_pcd, ren, wen, v_mem_read, dc_miss_ack,
       access2_reg, access2_combo, dc_rd_exp, io_ack, io_access;
  wire mem_rd_ready, mem_wr_done, mem_rd_busy, mem_wr_busy, dc_miss,
       dc_evict, dc_hit, dc_rd_hit, dc_wr_hit;
  wire n_0, n_1, n_2, n_3, n_5, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_64, n_67, w_tag_eq;
  eq_checker6 u_eq_checker6(.in1 (phy_tag), .in2 (ts_tag), .eq_out
       (w_tag_eq));
  nand2$ g1831(.in0 (n_28), .in1 (n_14), .out (mem_wr_done));
  nand2$ g1832(.in0 (n_29), .in1 (n_14), .out (mem_rd_ready));
  nand2$ g1833(.in0 (n_26), .in1 (n_25), .out (dc_hit));
  nor4$ g1834(.in0 (n_20), .in1 (n_22), .in2 (n_18), .in3 (io_access),
       .out (n_30));
  nand4$ g1835(.in0 (n_21), .in1 (n_17), .in2 (n_23), .in3 (n_8), .out
       (n_29));
  nand4$ g1836(.in0 (n_11), .in1 (n_17), .in2 (n_23), .in3 (n_8), .out
       (n_28));
  nor3$ g1837(.in0 (n_25), .in1 (n_18), .in2 (io_access), .out (n_27));
  nor4$ g1838(.in0 (n_9), .in1 (n_19), .in2 (n_24), .in3 (tlb_pcd),
       .out (dc_evict));
  nand2$ g1839(.in0 (n_23), .in1 (n_21), .out (n_26));
  nor2$ g1840(.in0 (n_22), .in1 (n_20), .out (dc_rd_hit));
  inv1$ g1841(.in (n_25), .out (dc_wr_hit));
  nand4$ g1842(.in0 (w_tag_eq), .in1 (wen), .in2 (n_12), .in3
       (ts_valid), .out (n_25));
  nor3$ g1843(.in0 (n_9), .in1 (n_24), .in2 (tlb_pcd), .out (dc_miss));
  nand2$ g1844(.in0 (n_16), .in1 (n_15), .out (n_24));
  nor3$ g1845(.in0 (tlb_pcd), .in1 (n_2), .in2 (dc_miss_ack), .out
       (n_23));
  nand3$ g1846(.in0 (n_3), .in1 (n_0), .in2 (ts_valid), .out (n_22));
  nor2$ g1847(.in0 (n_10), .in1 (dc_rd_exp), .out (n_21));
  nand3$ g1848(.in0 (ren), .in1 (n_5), .in2 (w_tag_eq), .out (n_20));
  nand3$ g1849(.in0 (ts_valid), .in1 (n_3), .in2 (ts_dirty), .out
       (n_19));
  nor2$ g1850(.in0 (n_1), .in1 (access2_reg), .out (n_18));
  nand2$ g1851(.in0 (n_7), .in1 (access2_combo), .out (n_17));
  nand2$ g1852(.in0 (ren), .in1 (dc_rd_exp), .out (n_16));
  nand2$ g1853(.in0 (ts_valid), .in1 (w_tag_eq), .out (n_15));
  nand2$ g1855(.in0 (io_ack), .in1 (io_access), .out (n_14));
  nor2$ g1856(.in0 (tlb_pcd), .in1 (dc_miss_ack), .out (n_12));
  and2$ g1857(.in0 (wen), .in1 (w_tag_eq), .out (n_11));
  nand2$ g1858(.in0 (ren), .in1 (w_tag_eq), .out (n_10));
  nor2$ g1859(.in0 (ren), .in1 (wen), .out (n_9));
  inv1$ g1860(.in (io_access), .out (n_8));
  inv1$ g1861(.in (access2_reg), .out (n_7));
  inv1$ g1863(.in (dc_rd_exp), .out (n_5));
  inv1$ g1865(.in (dc_miss_ack), .out (n_3));
  inv1$ g1866(.in (ts_valid), .out (n_2));
  inv1$ g1867(.in (access2_combo), .out (n_1));
  inv1$ g1868(.in (tlb_pcd), .out (n_0));
  nor2$ g2(.in0 (n_64), .in1 (n_30), .out (mem_rd_busy));
  nand2$ g3(.in0 (v_mem_read), .in1 (n_14), .out (n_64));
  nor2$ g1870(.in0 (n_67), .in1 (n_27), .out (mem_wr_busy));
  nand2$ g1871(.in0 (wen), .in1 (n_14), .out (n_67));
endmodule

