
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/evict_combo 

module evict_combo(dc_evict, dc_miss, dc_miss_ack, ts_valid2,
     ts_dirty2, ts_lru2, ts_valid1, ts_dirty1, ts_lru1, evict_way2,
     evict_way1);
  input dc_miss, dc_miss_ack, ts_valid2, ts_dirty2, ts_lru2, ts_valid1,
       ts_dirty1, ts_lru1;
  output dc_evict, evict_way2, evict_way1;
  wire dc_miss, dc_miss_ack, ts_valid2, ts_dirty2, ts_lru2, ts_valid1,
       ts_dirty1, ts_lru1;
  wire dc_evict, evict_way2, evict_way1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  nand2$ g669(.in0 (n_12), .in1 (n_11), .out (dc_evict));
  nor2$ g671(.in0 (n_6), .in1 (n_3), .out (evict_way2));
  nand2$ g670(.in0 (n_8), .in1 (ts_valid1), .out (evict_way1));
  nand4$ g672(.in0 (n_10), .in1 (n_9), .in2 (n_7), .in3 (ts_dirty1),
       .out (n_12));
  nand4$ g673(.in0 (n_10), .in1 (n_9), .in2 (n_5), .in3 (ts_dirty2),
       .out (n_11));
  nand2$ g674(.in0 (n_7), .in1 (ts_valid2), .out (n_8));
  nor2$ g675(.in0 (n_5), .in1 (n_4), .out (n_6));
  nor2$ g679(.in0 (n_4), .in1 (n_3), .out (n_9));
  nand2$ g676(.in0 (n_2), .in1 (ts_lru1), .out (n_7));
  nor2$ g677(.in0 (n_0), .in1 (ts_lru2), .out (n_5));
  nor2$ g678(.in0 (n_1), .in1 (dc_miss_ack), .out (n_10));
  inv1$ g684(.in (ts_valid1), .out (n_3));
  inv1$ g681(.in (ts_lru2), .out (n_2));
  inv1$ g682(.in (dc_miss), .out (n_1));
  inv1$ g683(.in (ts_lru1), .out (n_0));
  inv1$ g680(.in (ts_valid2), .out (n_4));
endmodule

