
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/ro_dep_v_ld_logic 

module ro_dep_v_ld_logic(V_ro, eip_change, in3, in4, in3_needed,
     in4_needed, seg3, seg3_needed, eax_needed, ecx_needed, wb_dreg1,
     wb_dreg2, wb_dreg3, v_wb_ld_reg1, v_wb_ld_reg2, v_wb_ld_reg3, mm1,
     mm2, mm1_needed, mm2_needed, wb_dmm, v_wb_ld_mm, wb_dseg,
     v_wb_ld_seg, wb_mem_stall, mem_rd_busy, cmps_stall, dc_exp,
     ld_reg1, ld_reg2, ld_reg3, ld_flag_ZF, ld_seg, v_ro_ld_reg1,
     v_ro_ld_reg2, v_ro_ld_reg3, v_ro_ld_flag_ZF, v_ro_ld_seg,
     dep_stall, br_stall, stall_ro, V_ex, ld_ex);
  input V_ro, eip_change, in3_needed, in4_needed, seg3_needed,
       eax_needed, ecx_needed, v_wb_ld_reg1, v_wb_ld_reg2,
       v_wb_ld_reg3, mm1_needed, mm2_needed, v_wb_ld_mm, v_wb_ld_seg,
       wb_mem_stall, mem_rd_busy, cmps_stall, dc_exp, ld_reg1, ld_reg2,
       ld_reg3, ld_flag_ZF, ld_seg;
  input [2:0] in3, in4, seg3, wb_dreg1, wb_dreg2, wb_dreg3, mm1, mm2,
       wb_dmm, wb_dseg;
  output v_ro_ld_reg1, v_ro_ld_reg2, v_ro_ld_reg3, v_ro_ld_flag_ZF,
       v_ro_ld_seg, dep_stall, br_stall, stall_ro, V_ex, ld_ex;
  wire V_ro, eip_change, in3_needed, in4_needed, seg3_needed,
       eax_needed, ecx_needed, v_wb_ld_reg1, v_wb_ld_reg2,
       v_wb_ld_reg3, mm1_needed, mm2_needed, v_wb_ld_mm, v_wb_ld_seg,
       wb_mem_stall, mem_rd_busy, cmps_stall, dc_exp, ld_reg1, ld_reg2,
       ld_reg3, ld_flag_ZF, ld_seg;
  wire [2:0] in3, in4, seg3, wb_dreg1, wb_dreg2, wb_dreg3, mm1, mm2,
       wb_dmm, wb_dseg;
  wire v_ro_ld_reg1, v_ro_ld_reg2, v_ro_ld_reg3, v_ro_ld_flag_ZF,
       v_ro_ld_seg, dep_stall, br_stall, stall_ro, V_ex, ld_ex;
  wire n_0, n_1, n_3, n_4, n_10, n_11, n_12, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_29, n_30, n_31;
  wire n_32, n_33, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_82, n_84, n_85;
  wire n_141, n_143, n_144, n_145, n_146;
  assign stall_ro = wb_mem_stall;
  nand4$ g17383(.in0 (n_80), .in1 (n_82), .in2 (n_79), .in3 (n_84),
       .out (dep_stall));
  nand3$ g17385(.in0 (n_77), .in1 (n_84), .in2 (n_47), .out (n_85));
  nand3$ g17390(.in0 (V_ro), .in1 (n_76), .in2 (in3_needed), .out
       (n_82));
  and2$ g17387(.in0 (n_78), .in1 (n_77), .out (n_79));
  nand3$ g17388(.in0 (V_ro), .in1 (n_74), .in2 (in4_needed), .out
       (n_84));
  nand3$ g17392(.in0 (V_ro), .in1 (n_73), .in2 (eax_needed), .out
       (n_77));
  nand2$ g17386(.in0 (n_75), .in1 (V_ro), .out (n_80));
  nand3$ g17394(.in0 (n_144), .in1 (n_70), .in2 (n_71), .out (n_76));
  nand3$ g17395(.in0 (V_ro), .in1 (n_69), .in2 (ecx_needed), .out
       (n_78));
  nand3$ g17391(.in0 (n_67), .in1 (n_68), .in2 (n_66), .out (n_75));
  nand3$ g17393(.in0 (n_64), .in1 (n_65), .in2 (n_63), .out (n_74));
  nand3$ g17398(.in0 (n_51), .in1 (n_54), .in2 (n_59), .out (n_73));
  nand4$ g17401(.in0 (n_32), .in1 (n_33), .in2 (n_60), .in3
       (v_wb_ld_reg3), .out (n_71));
  nand3$ g17396(.in0 (n_57), .in1 (n_56), .in2 (n_43), .out (n_70));
  nand3$ g17397(.in0 (n_50), .in1 (n_55), .in2 (n_62), .out (n_69));
  nand4$ g17400(.in0 (n_42), .in1 (n_23), .in2 (n_10), .in3 (n_41),
       .out (n_68));
  nand4$ g17402(.in0 (n_40), .in1 (n_22), .in2 (n_11), .in3 (n_39),
       .out (n_67));
  nand4$ g17403(.in0 (n_38), .in1 (n_21), .in2 (n_12), .in3 (n_37),
       .out (n_66));
  nand4$ g17404(.in0 (n_18), .in1 (n_19), .in2 (n_20), .in3
       (v_wb_ld_reg3), .out (n_65));
  nand4$ g17405(.in0 (n_15), .in1 (n_16), .in2 (n_17), .in3
       (v_wb_ld_reg1), .out (n_64));
  nand4$ g17406(.in0 (n_24), .in1 (n_25), .in2 (n_26), .in3
       (v_wb_ld_reg2), .out (n_63));
  nand3$ g17408(.in0 (wb_dreg1[0]), .in1 (n_58), .in2 (v_wb_ld_reg1),
       .out (n_62));
  nor2$ g17409(.in0 (n_14), .in1 (n_46), .out (n_61));
  nor2$ g17410(.in0 (n_45), .in1 (n_44), .out (n_60));
  nand3$ g17413(.in0 (n_30), .in1 (n_58), .in2 (v_wb_ld_reg1), .out
       (n_59));
  nor2$ g17415(.in0 (n_29), .in1 (n_27), .out (n_57));
  nor2$ g17416(.in0 (n_31), .in1 (n_4), .out (n_56));
  nand4$ g17407(.in0 (wb_dreg2[0]), .in1 (n_53), .in2 (n_52), .in3
       (v_wb_ld_reg2), .out (n_55));
  nand4$ g17411(.in0 (n_53), .in1 (n_52), .in2 (n_146), .in3
       (v_wb_ld_reg2), .out (n_54));
  nand4$ g17412(.in0 (n_49), .in1 (n_48), .in2 (n_1), .in3
       (v_wb_ld_reg3), .out (n_51));
  nand4$ g17414(.in0 (wb_dreg3[0]), .in1 (n_49), .in2 (n_48), .in3
       (v_wb_ld_reg3), .out (n_50));
  nor4$ g17425(.in0 (mem_rd_busy), .in1 (dc_exp), .in2 (n_3), .in3
       (cmps_stall), .out (n_47));
  xor2$ g17432(.in0 (in3[1]), .in1 (wb_dreg2[1]), .out (n_46));
  xor2$ g17433(.in0 (in3[2]), .in1 (wb_dreg3[2]), .out (n_45));
  xor2$ g17434(.in0 (in3[0]), .in1 (wb_dreg3[0]), .out (n_44));
  xnor2$ g17435(.in0 (in3[2]), .in1 (wb_dreg1[2]), .out (n_43));
  xnor2$ g17436(.in0 (mm1[2]), .in1 (wb_dmm[2]), .out (n_42));
  xnor2$ g17437(.in0 (mm1[1]), .in1 (wb_dmm[1]), .out (n_41));
  xnor2$ g17438(.in0 (mm2[2]), .in1 (wb_dmm[2]), .out (n_40));
  xnor2$ g17439(.in0 (mm2[1]), .in1 (wb_dmm[1]), .out (n_39));
  xnor2$ g17440(.in0 (seg3[2]), .in1 (wb_dseg[2]), .out (n_38));
  xnor2$ g17441(.in0 (seg3[1]), .in1 (wb_dseg[1]), .out (n_37));
  nand2$ g17444(.in0 (n_48), .in1 (in3[1]), .out (n_33));
  nand2$ g17445(.in0 (n_0), .in1 (wb_dreg3[1]), .out (n_32));
  nor2$ g17446(.in0 (n_30), .in1 (in3[0]), .out (n_31));
  nor2$ g17447(.in0 (n_145), .in1 (wb_dreg1[0]), .out (n_29));
  xor2$ g17417(.in0 (in3[1]), .in1 (wb_dreg1[1]), .out (n_27));
  xnor2$ g17418(.in0 (in4[0]), .in1 (wb_dreg2[0]), .out (n_26));
  xnor2$ g17419(.in0 (in4[2]), .in1 (wb_dreg2[2]), .out (n_25));
  xnor2$ g17420(.in0 (in4[1]), .in1 (wb_dreg2[1]), .out (n_24));
  xnor2$ g17421(.in0 (mm1[0]), .in1 (wb_dmm[0]), .out (n_23));
  xnor2$ g17422(.in0 (mm2[0]), .in1 (wb_dmm[0]), .out (n_22));
  xnor2$ g17423(.in0 (seg3[0]), .in1 (wb_dseg[0]), .out (n_21));
  xnor2$ g17424(.in0 (in4[0]), .in1 (wb_dreg3[0]), .out (n_20));
  xnor2$ g17426(.in0 (in4[2]), .in1 (wb_dreg3[2]), .out (n_19));
  xnor2$ g17427(.in0 (in4[1]), .in1 (wb_dreg3[1]), .out (n_18));
  xnor2$ g17428(.in0 (in4[2]), .in1 (wb_dreg1[2]), .out (n_17));
  xnor2$ g17429(.in0 (in4[1]), .in1 (wb_dreg1[1]), .out (n_16));
  xnor2$ g17430(.in0 (in4[0]), .in1 (wb_dreg1[0]), .out (n_15));
  xor2$ g17431(.in0 (in3[2]), .in1 (wb_dreg2[2]), .out (n_14));
  and2$ g17454(.in0 (V_ro), .in1 (eip_change), .out (br_stall));
  nor2$ g17448(.in0 (wb_dreg1[2]), .in1 (wb_dreg1[1]), .out (n_58));
  and2$ g17449(.in0 (seg3_needed), .in1 (v_wb_ld_seg), .out (n_12));
  and2$ g17452(.in0 (mm2_needed), .in1 (v_wb_ld_mm), .out (n_11));
  and2$ g17457(.in0 (mm1_needed), .in1 (v_wb_ld_mm), .out (n_10));
  and2$ g17450(.in0 (V_ro), .in1 (ld_reg2), .out (v_ro_ld_reg2));
  and2$ g17455(.in0 (V_ro), .in1 (ld_reg3), .out (v_ro_ld_reg3));
  and2$ g17456(.in0 (V_ro), .in1 (ld_reg1), .out (v_ro_ld_reg1));
  and2$ g17453(.in0 (V_ro), .in1 (ld_flag_ZF), .out (v_ro_ld_flag_ZF));
  and2$ g17451(.in0 (V_ro), .in1 (ld_seg), .out (v_ro_ld_seg));
  inv1$ g17460(.in (v_wb_ld_reg1), .out (n_4));
  inv1$ g17467(.in (wb_dreg1[0]), .out (n_30));
  inv1$ g17458(.in (wb_dreg2[2]), .out (n_53));
  inv1$ g17469(.in (V_ro), .out (n_3));
  inv1$ g17459(.in (wb_mem_stall), .out (ld_ex));
  inv1$ g17463(.in (wb_dreg3[1]), .out (n_48));
  inv1$ g17466(.in (wb_dreg3[0]), .out (n_1));
  inv1$ g17462(.in (in3[1]), .out (n_0));
  inv1$ g17464(.in (wb_dreg2[1]), .out (n_52));
  inv1$ g17465(.in (wb_dreg3[2]), .out (n_49));
  nor2$ g2(.in0 (n_141), .in1 (n_85), .out (V_ex));
  nand3$ g3(.in0 (n_80), .in1 (n_78), .in2 (n_82), .out (n_141));
  nand3$ g17470(.in0 (n_143), .in1 (n_61), .in2 (v_wb_ld_reg2), .out
       (n_144));
  xnor2$ g17471(.in0 (in3[0]), .in1 (wb_dreg2[0]), .out (n_143));
  inv1$ g17472(.in (in3[0]), .out (n_145));
  inv1$ g17473(.in (wb_dreg2[0]), .out (n_146));
endmodule

