
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dma_master_controller_fsm 

module dma_master_controller_fsm(clk, rst_n, curr_st, start_transfer,
     d_ready, num_trans_eq1, num_trans_eq2, trans_cnt_eq2, m_ack,
     int_clear);
  input clk, rst_n, start_transfer, d_ready, num_trans_eq1,
       num_trans_eq2, trans_cnt_eq2, m_ack, int_clear;
  output [2:0] curr_st;
  wire clk, rst_n, start_transfer, d_ready, num_trans_eq1,
       num_trans_eq2, trans_cnt_eq2, m_ack, int_clear;
  wire [2:0] curr_st;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_43;
  dff$ \curr_st_reg[0] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_25),
       .q (curr_st[0]), .qbar (UNCONNECTED));
  dff$ \curr_st_reg[2] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_24),
       .q (curr_st[2]), .qbar (UNCONNECTED0));
  nand4$ g567(.in0 (n_14), .in1 (n_17), .in2 (n_22), .in3 (n_7), .out
       (n_25));
  dff$ \curr_st_reg[1] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_23),
       .q (curr_st[1]), .qbar (UNCONNECTED1));
  nand4$ g570(.in0 (n_9), .in1 (n_4), .in2 (n_21), .in3 (n_11), .out
       (n_24));
  nand3$ g569(.in0 (n_5), .in1 (n_20), .in2 (n_12), .out (n_23));
  or2$ g568(.in0 (n_19), .in1 (n_8), .out (n_22));
  nand2$ g573(.in0 (n_16), .in1 (d_ready), .out (n_21));
  nand3$ g577(.in0 (n_3), .in1 (n_18), .in2 (m_ack), .out (n_20));
  mux2$ g571(.s0 (m_ack), .in0 (n_13), .in1 (n_18), .outb (n_19));
  or2$ g572(.in0 (n_15), .in1 (d_ready), .out (n_17));
  inv1$ g579(.in (n_15), .out (n_16));
  nand3$ g574(.in0 (n_13), .in1 (n_10), .in2 (start_transfer), .out
       (n_14));
  or2$ g575(.in0 (n_11), .in1 (n_6), .out (n_12));
  nand2$ g580(.in0 (n_10), .in1 (curr_st[0]), .out (n_15));
  or2$ g581(.in0 (n_8), .in1 (m_ack), .out (n_9));
  nand4$ g576(.in0 (curr_st[1]), .in1 (n_43), .in2 (n_6), .in3
       (curr_st[2]), .out (n_7));
  or4$ g578(.in0 (curr_st[2]), .in1 (curr_st[0]), .in2 (n_2), .in3
       (int_clear), .out (n_5));
  or3$ g582(.in0 (curr_st[0]), .in1 (n_1), .in2 (num_trans_eq1), .out
       (n_4));
  nand3$ g583(.in0 (n_0), .in1 (n_43), .in2 (num_trans_eq2), .out
       (n_18));
  nand3$ g584(.in0 (curr_st[1]), .in1 (n_13), .in2 (curr_st[2]), .out
       (n_11));
  inv1$ g586(.in (n_8), .out (n_3));
  and2$ g585(.in0 (n_2), .in1 (n_1), .out (n_10));
  nand2$ g587(.in0 (n_2), .in1 (curr_st[2]), .out (n_8));
  and2$ g588(.in0 (trans_cnt_eq2), .in1 (m_ack), .out (n_6));
  inv1$ g592(.in (num_trans_eq1), .out (n_0));
  inv1$ g589(.in (curr_st[1]), .out (n_2));
  inv1$ g591(.in (curr_st[0]), .out (n_13));
  inv1$ g590(.in (curr_st[2]), .out (n_1));
  inv1$ drc_bufs598(.in (curr_st[0]), .out (n_43));
endmodule

