
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dep_ld_mmx 

module dep_ld_mmx(mm1_needed_in, mm2_needed_in, sr1_rm, sr2_rm, mod,
     mod_rm_pr, ld_mm_in, ret_op, ld_mm, mm1_needed, mm2_needed,
     mm_sr1_sel_L, mm_sr2_sel);
  input mm1_needed_in, mm2_needed_in, sr1_rm, sr2_rm, mod_rm_pr,
       ld_mm_in, ret_op;
  input [1:0] mod;
  output ld_mm, mm1_needed, mm2_needed, mm_sr1_sel_L, mm_sr2_sel;
  wire mm1_needed_in, mm2_needed_in, sr1_rm, sr2_rm, mod_rm_pr,
       ld_mm_in, ret_op;
  wire [1:0] mod;
  wire ld_mm, mm1_needed, mm2_needed, mm_sr1_sel_L, mm_sr2_sel;
  wire n_0, n_1, n_4, n_5, n_7;
  and2$ g276(.in0 (n_7), .in1 (ld_mm_in), .out (ld_mm));
  and2$ g277(.in0 (n_7), .in1 (mm1_needed_in), .out (mm1_needed));
  and2$ g278(.in0 (n_5), .in1 (mm2_needed_in), .out (mm2_needed));
  nand2$ g279(.in0 (n_4), .in1 (sr1_rm), .out (n_7));
  nand2$ g280(.in0 (n_4), .in1 (sr2_rm), .out (n_5));
  nor2$ g283(.in0 (n_1), .in1 (n_0), .out (mm_sr1_sel_L));
  nor2$ g281(.in0 (n_1), .in1 (sr2_rm), .out (mm_sr2_sel));
  nand3$ g282(.in0 (mod[1]), .in1 (mod_rm_pr), .in2 (mod[0]), .out
       (n_4));
  and2$ g285(.in0 (mod[1]), .in1 (mod[0]), .out (n_1));
  or2$ g284(.in0 (sr1_rm), .in1 (ret_op), .out (n_0));
endmodule

