
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/test 

module test(in0, in1, in2, in3, sel, out);
  input in0, in1, in2, in3;
  input [1:0] sel;
  output out;
  wire in0, in1, in2, in3;
  wire [1:0] sel;
  wire out;
  mux4$ g57(.s1 (sel[0]), .s0 (sel[1]), .in0 (in0), .in1 (in2), .in2
       (in1), .in3 (in3), .outb (out));
endmodule

