
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/eq_checker 

module eq_checker16(in1, in2, eq_out);
  input [15:0] in1, in2;
  output eq_out;
  wire [15:0] in1, in2;
  wire eq_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  nor4$ g1160(.in0 (n_16), .in1 (n_17), .in2 (n_18), .in3 (n_19), .out
       (eq_out));
  nand4$ g1161(.in0 (n_11), .in1 (n_0), .in2 (n_6), .in3 (n_8), .out
       (n_19));
  nand4$ g1162(.in0 (n_15), .in1 (n_14), .in2 (n_1), .in3 (n_13), .out
       (n_18));
  nand4$ g1163(.in0 (n_3), .in1 (n_12), .in2 (n_5), .in3 (n_10), .out
       (n_17));
  nand4$ g1164(.in0 (n_2), .in1 (n_4), .in2 (n_7), .in3 (n_9), .out
       (n_16));
  xnor2$ g1165(.in0 (in1[13]), .in1 (in2[13]), .out (n_15));
  xnor2$ g1172(.in0 (in1[14]), .in1 (in2[14]), .out (n_14));
  xnor2$ g1173(.in0 (in1[12]), .in1 (in2[12]), .out (n_13));
  xnor2$ g1166(.in0 (in1[10]), .in1 (in2[10]), .out (n_12));
  xnor2$ g1174(.in0 (in1[1]), .in1 (in2[1]), .out (n_11));
  xnor2$ g1175(.in0 (in1[8]), .in1 (in2[8]), .out (n_10));
  xnor2$ g1167(.in0 (in1[4]), .in1 (in2[4]), .out (n_9));
  xnor2$ g1176(.in0 (in1[0]), .in1 (in2[0]), .out (n_8));
  xnor2$ g1177(.in0 (in1[7]), .in1 (in2[7]), .out (n_7));
  xnor2$ g1168(.in0 (in1[3]), .in1 (in2[3]), .out (n_6));
  xnor2$ g1178(.in0 (in1[11]), .in1 (in2[11]), .out (n_5));
  xnor2$ g1179(.in0 (in1[6]), .in1 (in2[6]), .out (n_4));
  xnor2$ g1169(.in0 (in1[9]), .in1 (in2[9]), .out (n_3));
  xnor2$ g1180(.in0 (in1[5]), .in1 (in2[5]), .out (n_2));
  xnor2$ g1170(.in0 (in1[15]), .in1 (in2[15]), .out (n_1));
  xnor2$ g1171(.in0 (in1[2]), .in1 (in2[2]), .out (n_0));
endmodule

