
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/pencoder_3_2 

module pencoder_3_2(a0, a1, a2, out);
  input a0, a1, a2;
  output [1:0] out;
  wire a0, a1, a2;
  wire [1:0] out;
  wire n_0, n_1, n_2, n_3;
  nand2$ g31(.in0 (n_2), .in1 (n_3), .out (out[0]));
  and2$ g30(.in0 (n_1), .in1 (n_3), .out (out[1]));
  nand2$ g33(.in0 (n_0), .in1 (a0), .out (n_2));
  or2$ g32(.in0 (a0), .in1 (a1), .out (n_1));
  inv1$ g34(.in (a1), .out (n_0));
  inv1$ g35(.in (a2), .out (n_3));
endmodule

