
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/wish_fsm 

module wish_fsm(clk, rst_n, m_mmu_cyc, m_mmu_ack, m_dma_cyc, m_dma_ack,
     curr_st);
  input clk, rst_n, m_mmu_cyc, m_mmu_ack, m_dma_cyc, m_dma_ack;
  output [2:0] curr_st;
  wire clk, rst_n, m_mmu_cyc, m_mmu_ack, m_dma_cyc, m_dma_ack;
  wire [2:0] curr_st;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_34;
  dff$ \curr_st_reg[0] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_18),
       .q (curr_st[0]), .qbar (UNCONNECTED));
  dff$ \curr_st_reg[2] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_19),
       .q (curr_st[2]), .qbar (UNCONNECTED0));
  dff$ \curr_st_reg[1] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_16),
       .q (curr_st[1]), .qbar (UNCONNECTED1));
  nand3$ g545(.in0 (n_13), .in1 (n_15), .in2 (n_17), .out (n_19));
  nand4$ g540(.in0 (n_10), .in1 (n_14), .in2 (n_11), .in3 (n_17), .out
       (n_18));
  nand2$ g542(.in0 (n_7), .in1 (n_12), .out (n_16));
  or2$ g546(.in0 (n_5), .in1 (n_9), .out (n_15));
  or2$ g547(.in0 (n_13), .in1 (m_dma_ack), .out (n_14));
  nand3$ g549(.in0 (n_8), .in1 (n_1), .in2 (curr_st[2]), .out (n_12));
  or2$ g543(.in0 (n_3), .in1 (m_mmu_ack), .out (n_11));
  or3$ g553(.in0 (n_0), .in1 (n_9), .in2 (curr_st[2]), .out (n_10));
  or3$ g554(.in0 (n_6), .in1 (n_8), .in2 (curr_st[1]), .out (n_17));
  nand4$ g544(.in0 (m_mmu_ack), .in1 (n_2), .in2 (n_6), .in3
       (m_mmu_cyc), .out (n_7));
  and2$ g550(.in0 (n_4), .in1 (n_34), .out (n_5));
  or2$ g552(.in0 (n_4), .in1 (n_34), .out (n_13));
  nand3$ g548(.in0 (n_2), .in1 (n_6), .in2 (m_mmu_cyc), .out (n_3));
  nand2$ g551(.in0 (n_9), .in1 (curr_st[0]), .out (n_1));
  nand2$ g556(.in0 (n_0), .in1 (m_dma_cyc), .out (n_4));
  or2$ g555(.in0 (curr_st[1]), .in1 (m_mmu_cyc), .out (n_9));
  nand2$ g557(.in0 (curr_st[0]), .in1 (curr_st[1]), .out (n_2));
  and2$ g558(.in0 (m_dma_cyc), .in1 (m_dma_ack), .out (n_8));
  inv1$ g559(.in (curr_st[0]), .out (n_0));
  inv1$ g560(.in (curr_st[2]), .out (n_6));
  inv1$ drc_bufs566(.in (curr_st[2]), .out (n_34));
endmodule

