
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/parity 

module parity(in, out);
  input [7:0] in;
  output out;
  wire [7:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  xnor2$ g164(.in0 (n_4), .in1 (n_5), .out (out));
  xnor2$ g165(.in0 (n_1), .in1 (n_0), .out (n_5));
  xnor2$ g166(.in0 (n_3), .in1 (n_2), .out (n_4));
  xnor2$ g168(.in0 (in[6]), .in1 (in[1]), .out (n_3));
  xnor2$ g169(.in0 (in[5]), .in1 (in[3]), .out (n_2));
  xnor2$ g167(.in0 (in[7]), .in1 (in[0]), .out (n_1));
  xnor2$ g170(.in0 (in[4]), .in1 (in[2]), .out (n_0));
endmodule

