
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/zero 

module zero16(in, out);
  input [15:0] in;
  output out;
  wire [15:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_41, n_42, n_43, n_44;
  nand4$ g220(.in0 (n_41), .in1 (n_43), .in2 (n_42), .in3 (n_44), .out
       (out));
  inv1$ g241(.in (in[3]), .out (n_15));
  inv1$ g237(.in (in[15]), .out (n_14));
  inv1$ g239(.in (in[0]), .out (n_13));
  inv1$ g229(.in (in[12]), .out (n_12));
  inv1$ g230(.in (in[13]), .out (n_11));
  inv1$ g232(.in (in[9]), .out (n_10));
  inv1$ g233(.in (in[6]), .out (n_9));
  inv1$ g234(.in (in[2]), .out (n_8));
  inv1$ g244(.in (in[1]), .out (n_7));
  inv1$ g235(.in (in[14]), .out (n_6));
  inv1$ g236(.in (in[4]), .out (n_5));
  inv1$ g238(.in (in[10]), .out (n_4));
  inv1$ g243(.in (in[11]), .out (n_3));
  inv1$ g240(.in (in[7]), .out (n_2));
  inv1$ g242(.in (in[5]), .out (n_1));
  inv1$ g231(.in (in[8]), .out (n_0));
  and4$ g2(.in0 (n_1), .in1 (n_9), .in2 (n_2), .in3 (n_5), .out (n_41));
  and4$ g245(.in0 (n_11), .in1 (n_6), .in2 (n_14), .in3 (n_12), .out
       (n_42));
  and4$ g246(.in0 (n_10), .in1 (n_4), .in2 (n_3), .in3 (n_0), .out
       (n_43));
  and4$ g247(.in0 (n_7), .in1 (n_8), .in2 (n_15), .in3 (n_13), .out
       (n_44));
endmodule

