
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/zero 
module zero32(in, out);
  input [31:0] in;
  output out;
  wire [31:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  nor2$ g546(.in0 (n_9), .in1 (n_8), .out (out));
  nand4$ g547(.in0 (n_0), .in1 (n_5), .in2 (n_3), .in3 (n_2), .out
       (n_9));
  nand4$ g548(.in0 (n_1), .in1 (n_4), .in2 (n_6), .in3 (n_7), .out
       (n_8));
  nor4$ g556(.in0 (in[1]), .in1 (in[2]), .in2 (in[3]), .in3 (in[0]),
       .out (n_7));
  nor4$ g549(.in0 (in[13]), .in1 (in[14]), .in2 (in[15]), .in3
       (in[12]), .out (n_6));
  nor4$ g552(.in0 (in[25]), .in1 (in[26]), .in2 (in[27]), .in3
       (in[24]), .out (n_5));
  nor4$ g553(.in0 (in[9]), .in1 (in[10]), .in2 (in[11]), .in3 (in[8]),
       .out (n_4));
  nor4$ g550(.in0 (in[29]), .in1 (in[30]), .in2 (in[31]), .in3
       (in[28]), .out (n_3));
  nor4$ g554(.in0 (in[17]), .in1 (in[18]), .in2 (in[19]), .in3
       (in[16]), .out (n_2));
  nor4$ g555(.in0 (in[5]), .in1 (in[6]), .in2 (in[7]), .in3 (in[4]),
       .out (n_1));
  nor4$ g551(.in0 (in[21]), .in1 (in[22]), .in2 (in[23]), .in3
       (in[20]), .out (n_0));
endmodule

module zero16(in, out);
  input [15:0] in;
  output out;
  wire [15:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  nor2$ g242(.in0 (n_9), .in1 (n_8), .out (out));
  nand4$ g243(.in0 (n_1), .in1 (n_5), .in2 (n_3), .in3 (n_4), .out
       (n_9));
  nand4$ g244(.in0 (n_7), .in1 (n_0), .in2 (n_2), .in3 (n_6), .out
       (n_8));
  nor2$ g250(.in0 (in[3]), .in1 (in[2]), .out (n_7));
  nor2$ g245(.in0 (in[1]), .in1 (in[0]), .out (n_6));
  nor2$ g251(.in0 (in[13]), .in1 (in[12]), .out (n_5));
  nor2$ g252(.in0 (in[9]), .in1 (in[8]), .out (n_4));
  nor2$ g246(.in0 (in[15]), .in1 (in[14]), .out (n_3));
  nor2$ g247(.in0 (in[7]), .in1 (in[6]), .out (n_2));
  nor2$ g248(.in0 (in[11]), .in1 (in[10]), .out (n_1));
  nor2$ g249(.in0 (in[5]), .in1 (in[4]), .out (n_0));
endmodule


module zero8(in, out);
  input [7:0] in;
  output out;
  wire [7:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  nor2$ g104(.in0 (n_5), .in1 (n_4), .out (out));
  nand2$ g105(.in0 (n_0), .in1 (n_2), .out (n_5));
  nand2$ g106(.in0 (n_3), .in1 (n_1), .out (n_4));
  nor2$ g107(.in0 (in[3]), .in1 (in[2]), .out (n_3));
  nor2$ g110(.in0 (in[5]), .in1 (in[4]), .out (n_2));
  nor2$ g108(.in0 (in[1]), .in1 (in[0]), .out (n_1));
  nor2$ g109(.in0 (in[7]), .in1 (in[6]), .out (n_0));
endmodule

module zero5(in, out);
  input [4:0] in;
  output out;
  wire [4:0] in;
  wire out;
  wire n_0, n_1, n_2;
  and3$ g67(.in0 (n_1), .in1 (n_2), .in2 (n_0), .out (out));
  nor2$ g68(.in0 (in[4]), .in1 (in[3]), .out (n_2));
  nor2$ g69(.in0 (in[2]), .in1 (in[1]), .out (n_1));
  inv1$ g70(.in (in[0]), .out (n_0));
endmodule



