
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/zero 

module zero32(in, out);
  input [31:0] in;
  output out;
  wire [31:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_48, n_49, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90;
  or2$ g351(.in0 (n_48), .in1 (n_49), .out (out));
  nand4$ g353(.in0 (n_84), .in1 (n_88), .in2 (n_85), .in3 (n_86), .out
       (n_49));
  nand4$ g352(.in0 (n_83), .in1 (n_87), .in2 (n_89), .in3 (n_90), .out
       (n_48));
  inv1$ g398(.in (in[13]), .out (n_31));
  inv1$ g386(.in (in[18]), .out (n_30));
  inv1$ g394(.in (in[5]), .out (n_29));
  inv1$ g378(.in (in[23]), .out (n_28));
  inv1$ g383(.in (in[9]), .out (n_27));
  inv1$ g384(.in (in[24]), .out (n_26));
  inv1$ g379(.in (in[3]), .out (n_25));
  inv1$ g382(.in (in[30]), .out (n_24));
  inv1$ g380(.in (in[27]), .out (n_23));
  inv1$ g376(.in (in[22]), .out (n_22));
  inv1$ g370(.in (in[20]), .out (n_21));
  inv1$ g399(.in (in[8]), .out (n_20));
  inv1$ g397(.in (in[25]), .out (n_19));
  inv1$ g395(.in (in[29]), .out (n_18));
  inv1$ g373(.in (in[17]), .out (n_17));
  inv1$ g391(.in (in[12]), .out (n_16));
  inv1$ g390(.in (in[26]), .out (n_15));
  inv1$ g374(.in (in[14]), .out (n_14));
  inv1$ g375(.in (in[11]), .out (n_13));
  inv1$ g372(.in (in[16]), .out (n_12));
  inv1$ g377(.in (in[2]), .out (n_11));
  inv1$ g396(.in (in[19]), .out (n_10));
  inv1$ g371(.in (in[21]), .out (n_9));
  inv1$ g381(.in (in[6]), .out (n_8));
  inv1$ g388(.in (in[1]), .out (n_7));
  inv1$ g392(.in (in[10]), .out (n_6));
  inv1$ g385(.in (in[28]), .out (n_5));
  inv1$ g387(.in (in[0]), .out (n_4));
  inv1$ g389(.in (in[15]), .out (n_3));
  inv1$ g393(.in (in[7]), .out (n_2));
  inv1$ g400(.in (in[4]), .out (n_1));
  inv1$ g401(.in (in[31]), .out (n_0));
  and4$ g2(.in0 (n_18), .in1 (n_24), .in2 (n_0), .in3 (n_5), .out
       (n_83));
  and4$ g402(.in0 (n_27), .in1 (n_6), .in2 (n_13), .in3 (n_20), .out
       (n_84));
  and4$ g403(.in0 (n_31), .in1 (n_14), .in2 (n_3), .in3 (n_16), .out
       (n_85));
  and4$ g404(.in0 (n_7), .in1 (n_11), .in2 (n_25), .in3 (n_4), .out
       (n_86));
  and4$ g405(.in0 (n_9), .in1 (n_22), .in2 (n_28), .in3 (n_21), .out
       (n_87));
  and4$ g406(.in0 (n_29), .in1 (n_8), .in2 (n_2), .in3 (n_1), .out
       (n_88));
  and4$ g407(.in0 (n_19), .in1 (n_15), .in2 (n_23), .in3 (n_26), .out
       (n_89));
  and4$ g408(.in0 (n_17), .in1 (n_30), .in2 (n_10), .in3 (n_12), .out
       (n_90));
endmodule

module zero16(in, out);
  input [15:0] in;
  output out;
  wire [15:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_41, n_42, n_43, n_44;
  nand4$ g220(.in0 (n_41), .in1 (n_43), .in2 (n_42), .in3 (n_44), .out
       (out));
  inv1$ g241(.in (in[3]), .out (n_15));
  inv1$ g237(.in (in[15]), .out (n_14));
  inv1$ g239(.in (in[0]), .out (n_13));
  inv1$ g229(.in (in[12]), .out (n_12));
  inv1$ g230(.in (in[13]), .out (n_11));
  inv1$ g232(.in (in[9]), .out (n_10));
  inv1$ g233(.in (in[6]), .out (n_9));
  inv1$ g234(.in (in[2]), .out (n_8));
  inv1$ g244(.in (in[1]), .out (n_7));
  inv1$ g235(.in (in[14]), .out (n_6));
  inv1$ g236(.in (in[4]), .out (n_5));
  inv1$ g238(.in (in[10]), .out (n_4));
  inv1$ g243(.in (in[11]), .out (n_3));
  inv1$ g240(.in (in[7]), .out (n_2));
  inv1$ g242(.in (in[5]), .out (n_1));
  inv1$ g231(.in (in[8]), .out (n_0));
  and4$ g2(.in0 (n_1), .in1 (n_9), .in2 (n_2), .in3 (n_5), .out (n_41));
  and4$ g245(.in0 (n_11), .in1 (n_6), .in2 (n_14), .in3 (n_12), .out
       (n_42));
  and4$ g246(.in0 (n_10), .in1 (n_4), .in2 (n_3), .in3 (n_0), .out
       (n_43));
  and4$ g247(.in0 (n_7), .in1 (n_8), .in2 (n_15), .in3 (n_13), .out
       (n_44));
endmodule


module zero8(in, out);
  input [7:0] in;
  output out;
  wire [7:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  or2$ g65(.in0 (n_9), .in1 (n_8), .out (out));
  nand4$ g66(.in0 (n_4), .in1 (n_7), .in2 (n_6), .in3 (n_5), .out
       (n_9));
  nand4$ g67(.in0 (n_0), .in1 (n_3), .in2 (n_1), .in3 (n_2), .out
       (n_8));
  inv1$ g68(.in (in[6]), .out (n_7));
  inv1$ g69(.in (in[7]), .out (n_6));
  inv1$ g70(.in (in[4]), .out (n_5));
  inv1$ g71(.in (in[5]), .out (n_4));
  inv1$ g72(.in (in[2]), .out (n_3));
  inv1$ g73(.in (in[0]), .out (n_2));
  inv1$ g74(.in (in[3]), .out (n_1));
  inv1$ g75(.in (in[1]), .out (n_0));
endmodule

module zero5(in, out);
  input [4:0] in;
  output out;
  wire [4:0] in;
  wire out;
  wire n_0, n_1, n_2, n_3, n_4;
  or2$ g41(.in0 (n_3), .in1 (n_4), .out (out));
  nand3$ g42(.in0 (n_0), .in1 (n_2), .in2 (n_1), .out (n_4));
  or2$ g43(.in0 (in[4]), .in1 (in[0]), .out (n_3));
  inv1$ g44(.in (in[1]), .out (n_2));
  inv1$ g46(.in (in[2]), .out (n_1));
  inv1$ g45(.in (in[3]), .out (n_0));
endmodule


