
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/mmu_fsm 

module mmu_fsm(clk, rst_n, ld_ro, io_access, io_rw, ic_miss, dc_miss,
     dc_evict_flag, mmu_ack, curr_st, next_st, count_eq3, count_eq7);
  input clk, rst_n, ld_ro, io_access, io_rw, ic_miss, dc_miss,
       dc_evict_flag, mmu_ack, count_eq3, count_eq7;
  output [2:0] curr_st, next_st;
  wire clk, rst_n, ld_ro, io_access, io_rw, ic_miss, dc_miss,
       dc_evict_flag, mmu_ack, count_eq3, count_eq7;
  wire [2:0] curr_st, next_st;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4;
  wire n_6, n_8, n_10, n_11, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_46, n_49, n_50, n_51, n_52, n_53, n_54;
  dff$ \curr_st_reg[0] (.r (rst_n), .s (1'b1), .clk (clk), .d
       (next_st[0]), .q (curr_st[0]), .qbar (UNCONNECTED));
  dff$ \curr_st_reg[2] (.r (rst_n), .s (1'b1), .clk (clk), .d
       (next_st[2]), .q (curr_st[2]), .qbar (UNCONNECTED0));
  nand2$ g1345(.in0 (n_27), .in1 (n_19), .out (next_st[0]));
  dff$ \curr_st_reg[1] (.r (rst_n), .s (1'b1), .clk (clk), .d
       (next_st[1]), .q (curr_st[1]), .qbar (UNCONNECTED1));
  nand3$ g1350(.in0 (n_15), .in1 (n_25), .in2 (n_49), .out
       (next_st[2]));
  nand2$ g1348(.in0 (n_26), .in1 (mmu_ack), .out (n_27));
  nand2$ g1349(.in0 (n_24), .in1 (n_23), .out (next_st[1]));
  nand3$ g1351(.in0 (n_51), .in1 (n_22), .in2 (n_52), .out (n_26));
  nand3$ g1353(.in0 (n_0), .in1 (n_21), .in2 (ic_miss), .out (n_25));
  nand2$ g1352(.in0 (n_20), .in1 (dc_miss), .out (n_24));
  nand2$ g1355(.in0 (n_16), .in1 (curr_st[1]), .out (n_23));
  nand4$ g1359(.in0 (io_access), .in1 (n_1), .in2 (n_17), .in3 (n_18),
       .out (n_22));
  nand2$ g1354(.in0 (n_53), .in1 (n_3), .out (n_21));
  nand2$ g1356(.in0 (n_54), .in1 (n_2), .out (n_20));
  nand3$ g1360(.in0 (n_18), .in1 (n_17), .in2 (curr_st[0]), .out
       (n_19));
  nand2$ g1361(.in0 (n_6), .in1 (curr_st[0]), .out (n_16));
  nand4$ g1358(.in0 (curr_st[0]), .in1 (n_10), .in2 (n_4), .in3
       (curr_st[1]), .out (n_15));
  and2$ g1366(.in0 (n_8), .in1 (n_10), .out (n_18));
  nand2$ g1367(.in0 (dc_evict_flag), .in1 (n_10), .out (n_6));
  or2$ g1365(.in0 (ic_miss), .in1 (dc_evict_flag), .out (n_4));
  nand2$ g1369(.in0 (curr_st[1]), .in1 (curr_st[2]), .out (n_3));
  nand2$ g1370(.in0 (curr_st[0]), .in1 (curr_st[2]), .out (n_2));
  inv1$ g1373(.in (curr_st[1]), .out (n_8));
  inv1$ g1377(.in (io_rw), .out (n_1));
  inv1$ g1371(.in (curr_st[2]), .out (n_10));
  inv1$ g1375(.in (dc_miss), .out (n_0));
  inv1$ g1374(.in (io_access), .out (n_11));
  inv1$ g1376(.in (ld_ro), .out (n_17));
  nand2$ g1381(.in0 (n_46), .in1 (curr_st[2]), .out (n_49));
  inv1$ g1382(.in (curr_st[0]), .out (n_46));
  nand3$ g1383(.in0 (n_50), .in1 (count_eq3), .in2 (curr_st[1]), .out
       (n_51));
  inv1$ drc_bufs1(.in (curr_st[0]), .out (n_50));
  nand4$ g1384(.in0 (n_8), .in1 (n_46), .in2 (count_eq7), .in3
       (curr_st[2]), .out (n_52));
  nand3$ g1385(.in0 (n_46), .in1 (n_11), .in2 (n_8), .out (n_53));
  nand3$ g1386(.in0 (n_50), .in1 (n_11), .in2 (n_10), .out (n_54));
endmodule

