/home/projects/courses/spring_18/ee382n-16120/lib/time -v2005 
/home/projects/courses/spring_18/ee382n-16120/lib/lib1 
/home/projects/courses/spring_18/ee382n-16120/lib/lib2 
/home/projects/courses/spring_18/ee382n-16120/lib/lib3 
/home/projects/courses/spring_18/ee382n-16120/lib/lib4 
/home/projects/courses/spring_18/ee382n-16120/lib/lib5 
/home/projects/courses/spring_18/ee382n-16120/lib/lib6 
../../reuse/sub_designs/mux3bit_2x1.v
../../reuse/sub_designs/mux4bit_2x1.v
../../reuse/sub_designs/mux4bit_3x1.v
../../reuse/sub_designs/mux2bit_2x1.v
../../reuse/sub_designs/eq_checker8_netlist.v
../../reuse/adders/cond_sum/cond_sum32.v
../../reuse/adders/cond_sum/cond_sum16.v
../../reuse/adders/cond_sum/cond_sum8.v
../../reuse/adders/cond_sum/cond_sum_abc.v
../../reuse/sub_designs/eq_checker.v 
../../reuse/sub_designs/mux4_32.v  
../../reuse/sub_designs/eq_checker16_netlist.v 
../../reuse/sub_designs/mux16bit_8x1.v         
../../reuse/sub_designs/mux32bit_2x1.v
../../reuse/sub_designs/eq_checker32_netlist.v  
../../reuse/sub_designs/mux32bit_4x1.v      
../../reuse/sub_designs/mux8bit_8x1.v      
../../reuse/sub_designs/eq_checker3_netlist.v   
../../reuse/sub_designs/mux32bit_16x1.v 
../../reuse/sub_designs/mux32bit_8x1.v   
../../reuse/sub_designs/mux_nbit_2x1.v 
../../reuse/shifters/mux_1bit.v
../../reuse/sub_designs/register.v
../../reuse/sub_designs/register_ld2bit.v
../../reuse/adders/kogge_stone/FA.v
../../reuse/adders/kogge_stone/kogge_stone.v
../../reuse/sub_designs/mux_4x1.v
../../reuse/sub_designs/mux_8x1.v
../../reuse/sub_designs/mux_16x1.v
../../reuse/sub_designs/demux_1x16.v
../../reuse/sub_designs/mux_nbit_4x1.v
../../reuse/sub_designs/mux_nbit_8x1.v
../../reuse/sub_designs/mux_nbit_8x1_mulsel.v
../../reuse/sub_designs/ram_nB_8w.v
../../reuse/shifters/shift_right_rotate.v
../../reuse/sub_designs/pencoder_3_2_netlist.v
../../reuse/sub_designs/AND1_nbit.v
fetch/i_cache.v
fetch/fetch_TLB_lookup.v
fetch/fetch_fsm.v
EIP_reg.v
decode/register_addr_dependency.v
decode/segment_addr_dependency.v
decode/mmx_addr_dependency.v
decode/dep_ld_reg_netlist.v
decode/dep_ld_mmx_netlist.v
decode/dependency_seg_netlist.v
decode/rom_value_select.v
decode/decode.v
regfile/regfile.v
regfile/mmx_regfile.v
regfile/seg_regfile.v
cpu.v
