
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/intexp_fsm 

module intexp_fsm(clk, rst_n, iret_op, int, ic_exp, dc_exp, end_bit,
     v_de, v_ag, v_ro, v_ex, v_wb, fifo_empty_bar, int_clear,
     block_ic_ren, rseq_mux_sel, curr_st);
  input clk, rst_n, iret_op, int, ic_exp, dc_exp, end_bit, v_de, v_ag,
       v_ro, v_ex, v_wb, fifo_empty_bar;
  output int_clear, block_ic_ren, rseq_mux_sel;
  output [2:0] curr_st;
  wire clk, rst_n, iret_op, int, ic_exp, dc_exp, end_bit, v_de, v_ag,
       v_ro, v_ex, v_wb, fifo_empty_bar;
  wire int_clear, block_ic_ren, rseq_mux_sel;
  wire [2:0] curr_st;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_14, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36;
  dff$ \curr_st_reg[0] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_36),
       .q (curr_st[0]), .qbar (UNCONNECTED));
  dff$ \curr_st_reg[1] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_35),
       .q (curr_st[1]), .qbar (UNCONNECTED0));
  dff$ \curr_st_reg[2] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_34),
       .q (curr_st[2]), .qbar (UNCONNECTED1));
  nand3$ g695(.in0 (n_32), .in1 (n_33), .in2 (n_31), .out (n_36));
  and3$ g696(.in0 (n_19), .in1 (n_30), .in2 (n_4), .out (n_35));
  nand3$ g697(.in0 (n_28), .in1 (n_33), .in2 (n_12), .out (n_34));
  or3$ g701(.in0 (n_21), .in1 (n_22), .in2 (n_27), .out (n_32));
  and2$ g698(.in0 (n_23), .in1 (n_16), .out (n_31));
  mux2$ g699(.s0 (n_29), .in0 (n_25), .in1 (n_26), .outb (n_30));
  nand3$ g703(.in0 (n_10), .in1 (n_29), .in2 (curr_st[1]), .out (n_33));
  nand2$ g702(.in0 (n_29), .in1 (n_20), .out (n_28));
  and2$ g706(.in0 (n_26), .in1 (n_25), .out (n_27));
  and2$ g705(.in0 (int), .in1 (n_14), .out (int_clear));
  nand3$ g700(.in0 (n_18), .in1 (n_11), .in2 (n_17), .out (n_23));
  or2$ g707(.in0 (n_22), .in1 (n_21), .out (n_29));
  inv1$ g711(.in (n_25), .out (n_20));
  nand2$ g704(.in0 (n_18), .in1 (n_17), .out (n_19));
  or2$ g712(.in0 (n_5), .in1 (curr_st[1]), .out (n_25));
  nand2$ g713(.in0 (n_8), .in1 (rseq_mux_sel), .out (n_16));
  inv1$ g714(.in (n_26), .out (n_14));
  inv1$ g708(.in (block_ic_ren), .out (n_17));
  nand2$ g710(.in0 (n_7), .in1 (rseq_mux_sel), .out (n_12));
  nand3$ g715(.in0 (curr_st[1]), .in1 (n_9), .in2 (curr_st[0]), .out
       (n_26));
  nand4$ g717(.in0 (n_1), .in1 (n_2), .in2 (n_3), .in3 (n_0), .out
       (n_22));
  or3$ g709(.in0 (curr_st[1]), .in1 (curr_st[2]), .in2 (curr_st[0]),
       .out (block_ic_ren));
  or3$ g716(.in0 (ic_exp), .in1 (int), .in2 (dc_exp), .out (n_11));
  and2$ g718(.in0 (n_9), .in1 (n_6), .out (n_10));
  nand2$ g719(.in0 (n_7), .in1 (n_6), .out (n_8));
  nand2$ g721(.in0 (n_9), .in1 (curr_st[0]), .out (n_5));
  or2$ g722(.in0 (n_9), .in1 (curr_st[1]), .out (n_4));
  or2$ g720(.in0 (v_wb), .in1 (fifo_empty_bar), .out (n_21));
  and2$ g723(.in0 (curr_st[2]), .in1 (curr_st[1]), .out (rseq_mux_sel));
  inv1$ g728(.in (v_de), .out (n_3));
  inv1$ g725(.in (curr_st[2]), .out (n_9));
  inv1$ g724(.in (curr_st[0]), .out (n_6));
  inv1$ g726(.in (v_ag), .out (n_2));
  inv1$ g727(.in (v_ro), .out (n_1));
  inv1$ g731(.in (end_bit), .out (n_7));
  inv1$ g730(.in (iret_op), .out (n_18));
  inv1$ g729(.in (v_ex), .out (n_0));
endmodule

