/home/projects/courses/spring_18/ee382n-16120/lib/time
/home/projects/courses/spring_18/ee382n-16120/lib/lib1
/home/projects/courses/spring_18/ee382n-16120/lib/lib2
/home/projects/courses/spring_18/ee382n-16120/lib/lib3
/home/projects/courses/spring_18/ee382n-16120/lib/lib4
/home/projects/courses/spring_18/ee382n-16120/lib/lib5
/home/projects/courses/spring_18/ee382n-16120/lib/lib6
../../rtl/reuse/adders/cond_sum/cond_sum8.v
../../rtl/reuse/adders/cond_sum/cond_sum16.v
../../rtl/reuse/adders/cond_sum/cond_sum32.v
../../rtl/reuse/adders/cond_sum/wallace_abc_adder.v
../../rtl/reuse/sub_designs/eq_checker16_netlist.v 	     
../../rtl/reuse/sub_designs/eq_checker32_netlist.v  	     
../../rtl/reuse/sub_designs/eq_checker3_netlist.v   
../../rtl/reuse/sub_designs/mux32bit_2x1.v
../../rtl/reuse/sub_designs/mux32bit_4x1.v	 
../../rtl/reuse/sub_designs/register.v
../../rtl/trunk/dma/dma_master_controller_fsm_netlist.v  
../../rtl/trunk/dma/dma_master_controller.v	
../../rtl/trunk/dma/dma_master_if.v	
../../rtl/trunk/dma/dma_slave_if.v	
../../rtl/trunk/dma/dma.v
../../rtl/trunk/disk/disk.v
../../rtl/trunk/disk/disk_top.v
../../rtl/trunk/keyboard/keyboard.v
../../rtl/trunk/main_mem/main_mem.v
../../rtl/trunk/main_mem/mem_array.v
../../rtl/trunk/main_mem/mem_fsm_netlist.v
../../rtl/trunk/wish_bus/wish_bus.v
../../rtl/trunk/wish_bus/wish_fsm_netlist.v
./system.v
