/home/projects/courses/spring_18/ee382n-16120/lib/time -v2005 
/home/projects/courses/spring_18/ee382n-16120/lib/lib1 
/home/projects/courses/spring_18/ee382n-16120/lib/lib2 
/home/projects/courses/spring_18/ee382n-16120/lib/lib3 
/home/projects/courses/spring_18/ee382n-16120/lib/lib4 
/home/projects/courses/spring_18/ee382n-16120/lib/lib5 
/home/projects/courses/spring_18/ee382n-16120/lib/lib6 

../../rtl/reuse/sub_designs/mux3bit_2x1.v
../../rtl/reuse/sub_designs/mux4bit_2x1.v
../../rtl/reuse/sub_designs/mux4bit_3x1.v
../../rtl/reuse/sub_designs/mux2bit_2x1.v
../../rtl/reuse/sub_designs/eq_checker8_netlist.v
../../rtl/reuse/adders/cond_sum/wallace_abc_adder.v
../../rtl/reuse/adders/cond_sum/cond_sum32.v
../../rtl/reuse/adders/cond_sum/cond_sum16.v
../../rtl/reuse/adders/cond_sum/cond_sum8.v
../../rtl/reuse/adders/cond_sum/cond_sum_abc.v
../../rtl/reuse/sub_designs/eq_checker.v 
../../rtl/reuse/sub_designs/mux4_32.v  
../../rtl/reuse/sub_designs/eq_checker16_netlist.v 
../../rtl/reuse/sub_designs/mux16bit_8x1.v         
../../rtl/reuse/sub_designs/mux32bit_2x1.v
../../rtl/reuse/sub_designs/eq_checker32_netlist.v  
../../rtl/reuse/sub_designs/mux32bit_4x1.v      
../../rtl/reuse/sub_designs/mux8bit_8x1.v      
../../rtl/reuse/sub_designs/eq_checker3_netlist.v   
../../rtl/reuse/sub_designs/mux32bit_16x1.v 
../../rtl/reuse/sub_designs/mux32bit_8x1.v   
../../rtl/reuse/sub_designs/mux_nbit_2x1.v 
../../rtl/reuse/shifters/mux_1bit.v
../../rtl/reuse/sub_designs/register.v
../../rtl/reuse/sub_designs/register_ld2bit.v
../../rtl/reuse/adders/kogge_stone/FA.v
../../rtl/reuse/adders/kogge_stone/kogge_stone.v
../../rtl/reuse/sub_designs/mux_4x1.v
../../rtl/reuse/sub_designs/mux_8x1.v
../../rtl/reuse/sub_designs/mux_16x1.v
../../rtl/reuse/sub_designs/demux_1x16.v
../../rtl/reuse/sub_designs/mux_nbit_4x1.v
../../rtl/reuse/sub_designs/mux_nbit_8x1.v
../../rtl/reuse/sub_designs/mux_nbit_8x1_mulsel.v
../../rtl/reuse/sub_designs/ram_nB_8w.v
../../rtl/reuse/shifters/shift_right_rotate.v
../../rtl/reuse/sub_designs/pencoder_3_2_netlist.v
../../rtl/reuse/sub_designs/AND1_nbit.v

../../rtl/trunk/cpu/fetch/i_cache.v
../../rtl/trunk/cpu/fetch/fetch_TLB_lookup.v
../../rtl/trunk/cpu/fetch/fetch_fsm.v

../../rtl/trunk/cpu/decode/register_addr_dependency.v
../../rtl/trunk/cpu/decode/segment_addr_dependency.v
../../rtl/trunk/cpu/decode/mmx_addr_dependency.v
../../rtl/trunk/cpu/decode/dep_ld_reg_netlist.v
../../rtl/trunk/cpu/decode/dep_ld_mmx_netlist.v
../../rtl/trunk/cpu/decode/dependency_seg_netlist.v
../../rtl/trunk/cpu/decode/rom_value_select.v
../../rtl/trunk/cpu/decode/decode.v

../../rtl/trunk/cpu/regfile/regfile.v
../../rtl/trunk/cpu/regfile/mmx_regfile.v
../../rtl/trunk/cpu/regfile/seg_regfile.v

../../rtl/trunk/cpu/execute/alu1.v
../../rtl/trunk/cpu/execute/alu2.v
../../rtl/trunk/cpu/execute/alu3.v
../../rtl/trunk/cpu/execute/or.v
../../rtl/trunk/cpu/execute/and.v
../../rtl/trunk/cpu/execute/not.v
../../rtl/trunk/cpu/execute/bit_shift_left_flgs.v
../../rtl/trunk/cpu/execute/bit_shift_right_flgs.v
../../rtl/trunk/cpu/execute/compare_netlist.v
../../rtl/trunk/cpu/execute/cond_sum32_c.v
../../rtl/trunk/cpu/execute/cond_sum16_c.v
../../rtl/trunk/cpu/execute/cond_sum8_c.v
../../rtl/trunk/cpu/execute/parity_netlist.v
../../rtl/trunk/cpu/execute/zero_sizes.v

../../rtl/trunk/dma/dma_master_controller_fsm_netlist.v  
../../rtl/trunk/dma/dma_master_controller.v
../../rtl/trunk/dma/dma_master_if.v
../../rtl/trunk/dma/dma_slave_if.v
../../rtl/trunk/dma/dma.v
../../rtl/trunk/disk/disk.v
../../rtl/trunk/disk/disk_top.v
../../rtl/trunk/keyboard/keyboard.v
../../rtl/trunk/main_mem/main_mem.v
../../rtl/trunk/main_mem/mem_array.v
../../rtl/trunk/main_mem/mem_fsm_netlist.v
../../rtl/trunk/wish_bus/wish_bus.v
../../rtl/trunk/wish_bus/wish_fsm_netlist.v

../../rtl/trunk/system/system.v
testbench.v
