
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/adderNbit 

module adder2bit(a, b, sum);
  input [1:0] a, b;
  output [1:0] sum;
  wire [1:0] a, b;
  wire [1:0] sum;
  wire n_0, n_1;
  xor2$ g91(.in0 (n_1), .in1 (n_0), .out (sum[1]));
  xor2$ g93(.in0 (a[0]), .in1 (b[0]), .out (sum[0]));
  xnor2$ g92(.in0 (a[1]), .in1 (b[1]), .out (n_1));
  nand2$ g94(.in0 (a[0]), .in1 (b[0]), .out (n_0));
endmodule

