
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/adderNbit_carry 

module adderNbit_carry(a, b, sum, cout);
  input [2:0] a, b;
  output [2:0] sum;
  output cout;
  wire [2:0] a, b;
  wire [2:0] sum;
  wire cout;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_10, n_11;
  nand2$ g599(.in0 (n_11), .in1 (n_2), .out (cout));
  xnor2$ g600(.in0 (n_10), .in1 (n_5), .out (sum[2]));
  or2$ g601(.in0 (n_10), .in1 (n_1), .out (n_11));
  nor2$ g603(.in0 (n_8), .in1 (n_3), .out (n_10));
  xor2$ g602(.in0 (n_6), .in1 (n_7), .out (sum[1]));
  nor2$ g605(.in0 (n_7), .in1 (n_0), .out (n_8));
  xnor2$ g604(.in0 (a[1]), .in1 (b[1]), .out (n_6));
  xor2$ g606(.in0 (a[2]), .in1 (b[2]), .out (n_5));
  xor2$ g607(.in0 (a[0]), .in1 (b[0]), .out (sum[0]));
  and2$ g609(.in0 (a[1]), .in1 (b[1]), .out (n_3));
  nand2$ g611(.in0 (a[2]), .in1 (b[2]), .out (n_2));
  nor2$ g612(.in0 (a[2]), .in1 (b[2]), .out (n_1));
  nor2$ g608(.in0 (a[1]), .in1 (b[1]), .out (n_0));
  nand2$ g610(.in0 (a[0]), .in1 (b[0]), .out (n_7));
endmodule

