
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/adderNbit 

module adderNbit(a, b, sum);
  input [2:0] a, b;
  output [2:0] sum;
  wire [2:0] a, b;
  wire [2:0] sum;
  wire n_0, n_1, n_2, n_5, n_17, n_18, n_19;
  xnor2$ g631(.in0 (n_18), .in1 (n_2), .out (sum[2]));
  xor2$ g632(.in0 (n_5), .in1 (n_19), .out (sum[1]));
  xor2$ g637(.in0 (a[0]), .in1 (b[0]), .out (sum[0]));
  xnor2$ g634(.in0 (a[1]), .in1 (b[1]), .out (n_5));
  xnor2$ g636(.in0 (a[2]), .in1 (b[2]), .out (n_2));
  or2$ g638(.in0 (a[1]), .in1 (b[1]), .out (n_1));
  nand2$ g641(.in0 (a[1]), .in1 (b[1]), .out (n_0));
  nand2$ g2(.in0 (n_17), .in1 (n_0), .out (n_18));
  nand3$ g3(.in0 (a[0]), .in1 (b[0]), .in2 (n_1), .out (n_17));
  nand2$ g642(.in0 (a[0]), .in1 (b[0]), .out (n_19));
endmodule

