
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/dma_master_controller_fsm 

module dma_master_controller_fsm(clk, rst_n, curr_st, start_transfer,
     d_ready, num_trans_eq1, num_trans_eq2, trans_cnt_eq2, m_ack,
     int_clear);
  input clk, rst_n, start_transfer, d_ready, num_trans_eq1,
       num_trans_eq2, trans_cnt_eq2, m_ack, int_clear;
  output [2:0] curr_st;
  wire clk, rst_n, start_transfer, d_ready, num_trans_eq1,
       num_trans_eq2, trans_cnt_eq2, m_ack, int_clear;
  wire [2:0] curr_st;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  dff$ \curr_st_reg[0] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_28),
       .q (curr_st[0]), .qbar (UNCONNECTED));
  dff$ \curr_st_reg[1] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_26),
       .q (curr_st[1]), .qbar (UNCONNECTED0));
  dff$ \curr_st_reg[2] (.r (rst_n), .s (1'b1), .clk (clk), .d (n_27),
       .q (curr_st[2]), .qbar (UNCONNECTED1));
  nand3$ g2026(.in0 (n_25), .in1 (n_24), .in2 (n_21), .out (n_28));
  nand4$ g2029(.in0 (n_22), .in1 (n_16), .in2 (n_7), .in3 (n_11), .out
       (n_27));
  nand3$ g2027(.in0 (n_20), .in1 (n_23), .in2 (n_8), .out (n_26));
  nand4$ g2030(.in0 (num_trans_eq2), .in1 (m_ack), .in2 (n_5), .in3
       (n_17), .out (n_25));
  nor3$ g2028(.in0 (n_10), .in1 (n_9), .in2 (n_18), .out (n_24));
  nand3$ g2037(.in0 (m_ack), .in1 (n_6), .in2 (n_4), .out (n_23));
  nand2$ g2032(.in0 (d_ready), .in1 (n_14), .out (n_22));
  nand3$ g2034(.in0 (m_ack), .in1 (trans_cnt_eq2), .in2 (n_19), .out
       (n_21));
  nand2$ g2031(.in0 (n_0), .in1 (n_19), .out (n_20));
  nor3$ g2035(.in0 (n_13), .in1 (d_ready), .in2 (n_12), .out (n_18));
  nor2$ g2041(.in0 (n_15), .in1 (curr_st[0]), .out (n_17));
  or2$ g2042(.in0 (m_ack), .in1 (n_15), .out (n_16));
  nor2$ g2043(.in0 (n_13), .in1 (n_12), .out (n_14));
  inv1$ g2044(.in (n_19), .out (n_11));
  nor3$ g2033(.in0 (n_15), .in1 (m_ack), .in2 (n_12), .out (n_10));
  and3$ g2036(.in0 (n_2), .in1 (start_transfer), .in2 (n_12), .out
       (n_9));
  or4$ g2038(.in0 (curr_st[0]), .in1 (n_3), .in2 (int_clear), .in3
       (curr_st[2]), .out (n_8));
  nand2$ g2039(.in0 (n_1), .in1 (curr_st[2]), .out (n_7));
  nand3$ g2040(.in0 (num_trans_eq2), .in1 (n_5), .in2 (n_12), .out
       (n_6));
  and3$ g2045(.in0 (curr_st[1]), .in1 (n_12), .in2 (curr_st[2]), .out
       (n_19));
  inv1$ g2046(.in (n_15), .out (n_4));
  nand2$ g2047(.in0 (n_3), .in1 (curr_st[2]), .out (n_15));
  inv1$ g2050(.in (n_2), .out (n_13));
  nor2$ g2049(.in0 (num_trans_eq1), .in1 (curr_st[0]), .out (n_1));
  nand2$ g2048(.in0 (trans_cnt_eq2), .in1 (m_ack), .out (n_0));
  nor2$ g2051(.in0 (curr_st[1]), .in1 (curr_st[2]), .out (n_2));
  inv1$ g2053(.in (curr_st[0]), .out (n_12));
  inv1$ g2052(.in (curr_st[1]), .out (n_3));
  inv1$ g2054(.in (num_trans_eq1), .out (n_5));
endmodule

