
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/eq_checker 

module eq_checker20(in1, in2, eq_out);
  input [19:0] in1, in2;
  output eq_out;
  wire [19:0] in1, in2;
  wire eq_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25;
  and3$ g1216(.in0 (n_21), .in1 (n_25), .in2 (n_23), .out (eq_out));
  and3$ g1217(.in0 (n_22), .in1 (n_24), .in2 (n_20), .out (n_25));
  and4$ g1222(.in0 (n_15), .in1 (n_18), .in2 (n_4), .in3 (n_5), .out
       (n_24));
  and4$ g1220(.in0 (n_2), .in1 (n_8), .in2 (n_0), .in3 (n_9), .out
       (n_23));
  and4$ g1218(.in0 (n_10), .in1 (n_14), .in2 (n_19), .in3 (n_7), .out
       (n_22));
  and4$ g1219(.in0 (n_11), .in1 (n_13), .in2 (n_16), .in3 (n_12), .out
       (n_21));
  and4$ g1221(.in0 (n_1), .in1 (n_3), .in2 (n_6), .in3 (n_17), .out
       (n_20));
  xnor2$ g1227(.in0 (in1[19]), .in1 (in2[19]), .out (n_19));
  xnor2$ g1240(.in0 (in1[9]), .in1 (in2[9]), .out (n_18));
  xnor2$ g1241(.in0 (in1[0]), .in1 (in2[0]), .out (n_17));
  xnor2$ g1228(.in0 (in1[15]), .in1 (in2[15]), .out (n_16));
  xnor2$ g1242(.in0 (in1[11]), .in1 (in2[11]), .out (n_15));
  xnor2$ g1229(.in0 (in1[18]), .in1 (in2[18]), .out (n_14));
  xnor2$ g1230(.in0 (in1[14]), .in1 (in2[14]), .out (n_13));
  xnor2$ g1231(.in0 (in1[12]), .in1 (in2[12]), .out (n_12));
  xnor2$ g1223(.in0 (in1[13]), .in1 (in2[13]), .out (n_11));
  xnor2$ g1232(.in0 (in1[17]), .in1 (in2[17]), .out (n_10));
  xnor2$ g1233(.in0 (in1[4]), .in1 (in2[4]), .out (n_9));
  xnor2$ g1224(.in0 (in1[6]), .in1 (in2[6]), .out (n_8));
  xnor2$ g1234(.in0 (in1[16]), .in1 (in2[16]), .out (n_7));
  xnor2$ g1235(.in0 (in1[3]), .in1 (in2[3]), .out (n_6));
  xnor2$ g1225(.in0 (in1[8]), .in1 (in2[8]), .out (n_5));
  xnor2$ g1236(.in0 (in1[10]), .in1 (in2[10]), .out (n_4));
  xnor2$ g1237(.in0 (in1[2]), .in1 (in2[2]), .out (n_3));
  xnor2$ g1226(.in0 (in1[5]), .in1 (in2[5]), .out (n_2));
  xnor2$ g1238(.in0 (in1[1]), .in1 (in2[1]), .out (n_1));
  xnor2$ g1239(.in0 (in1[7]), .in1 (in2[7]), .out (n_0));
endmodule

