
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/eq_checker8 

module eq_checker8(in1, in2, eq_out);
  input [7:0] in1, in2;
  output eq_out;
  wire [7:0] in1, in2;
  wire eq_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  and2$ g562(.in0 (n_8), .in1 (n_9), .out (eq_out));
  and4$ g564(.in0 (n_7), .in1 (n_6), .in2 (n_2), .in3 (n_4), .out
       (n_9));
  and4$ g563(.in0 (n_1), .in1 (n_0), .in2 (n_3), .in3 (n_5), .out
       (n_8));
  xnor2$ g568(.in0 (in1[1]), .in1 (in2[1]), .out (n_7));
  xnor2$ g565(.in0 (in1[2]), .in1 (in2[2]), .out (n_6));
  xnor2$ g569(.in0 (in1[4]), .in1 (in2[4]), .out (n_5));
  xnor2$ g570(.in0 (in1[0]), .in1 (in2[0]), .out (n_4));
  xnor2$ g566(.in0 (in1[7]), .in1 (in2[7]), .out (n_3));
  xnor2$ g571(.in0 (in1[3]), .in1 (in2[3]), .out (n_2));
  xnor2$ g572(.in0 (in1[5]), .in1 (in2[5]), .out (n_1));
  xnor2$ g567(.in0 (in1[6]), .in1 (in2[6]), .out (n_0));
endmodule

