
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/greater_than_for_af 

module greater_than_for_af(in1, in2, gt_out);
  input [3:0] in1, in2;
  output gt_out;
  wire [3:0] in1, in2;
  wire gt_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  nand3$ g639(.in0 (n_10), .in1 (n_12), .in2 (n_6), .out (gt_out));
  nand4$ g640(.in0 (n_9), .in1 (n_8), .in2 (n_11), .in3 (n_2), .out
       (n_12));
  nand2$ g641(.in0 (n_7), .in1 (in2[1]), .out (n_11));
  nand3$ g644(.in0 (n_1), .in1 (n_9), .in2 (in1[2]), .out (n_10));
  nand2$ g642(.in0 (n_4), .in1 (n_0), .out (n_8));
  nand3$ g643(.in0 (in1[1]), .in1 (n_3), .in2 (in1[0]), .out (n_7));
  nand2$ g647(.in0 (n_5), .in1 (in1[3]), .out (n_6));
  or2$ g648(.in0 (n_5), .in1 (in1[3]), .out (n_9));
  nand2$ g645(.in0 (n_3), .in1 (in1[0]), .out (n_4));
  or2$ g646(.in0 (n_1), .in1 (in1[2]), .out (n_2));
  inv1$ g652(.in (in1[1]), .out (n_0));
  inv1$ g649(.in (in2[2]), .out (n_1));
  inv1$ g650(.in (in2[0]), .out (n_3));
  inv1$ g651(.in (in2[3]), .out (n_5));
endmodule

