
// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1

// Verification Directory fv/greater_than_for_flags 

module greater_than_for_flags8(in1, in2, gt_out);
  input [7:0] in1, in2;
  output gt_out;
  wire [7:0] in1, in2;
  wire gt_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40;
  nor2$ g4206(.in0 (n_40), .in1 (n_39), .out (gt_out));
  nor2$ g4208(.in0 (n_37), .in1 (n_38), .out (n_40));
  nand2$ g4207(.in0 (n_35), .in1 (n_36), .out (n_39));
  nand3$ g4212(.in0 (n_13), .in1 (n_34), .in2 (n_8), .out (n_38));
  nor2$ g4211(.in0 (n_33), .in1 (n_31), .out (n_37));
  nand2$ g4209(.in0 (n_30), .in1 (n_32), .out (n_36));
  nand2$ g4210(.in0 (n_34), .in1 (n_28), .out (n_35));
  nor2$ g4214(.in0 (n_29), .in1 (n_27), .out (n_33));
  nand2$ g4213(.in0 (n_26), .in1 (n_5), .out (n_32));
  nor3$ g4215(.in0 (n_18), .in1 (n_21), .in2 (n_17), .out (n_34));
  nand2$ g4216(.in0 (n_12), .in1 (n_9), .out (n_31));
  nand2$ g4217(.in0 (n_15), .in1 (in1[7]), .out (n_30));
  nand2$ g4218(.in0 (n_24), .in1 (n_23), .out (n_29));
  nand2$ g4219(.in0 (n_20), .in1 (n_11), .out (n_28));
  nor2$ g4221(.in0 (n_25), .in1 (n_19), .out (n_27));
  nand2$ g4220(.in0 (n_7), .in1 (in2[6]), .out (n_26));
  nor2$ g4226(.in0 (n_22), .in1 (in1[1]), .out (n_25));
  nand2$ g4227(.in0 (n_1), .in1 (in1[2]), .out (n_24));
  nand2$ g4228(.in0 (n_22), .in1 (in1[1]), .out (n_23));
  nor2$ g4229(.in0 (n_14), .in1 (in2[6]), .out (n_21));
  nand2$ g4235(.in0 (n_16), .in1 (in2[5]), .out (n_20));
  nand2$ g4230(.in0 (n_0), .in1 (in1[0]), .out (n_19));
  nor2$ g4231(.in0 (n_2), .in1 (in2[7]), .out (n_18));
  nor2$ g4232(.in0 (n_16), .in1 (in2[5]), .out (n_17));
  nand2$ g4233(.in0 (n_14), .in1 (in2[6]), .out (n_15));
  or2$ g4234(.in0 (n_10), .in1 (in2[4]), .out (n_13));
  nand2$ g4222(.in0 (n_4), .in1 (in2[3]), .out (n_12));
  nand2$ g4223(.in0 (n_10), .in1 (in2[4]), .out (n_11));
  nand2$ g4224(.in0 (n_3), .in1 (in2[2]), .out (n_9));
  nand2$ g4225(.in0 (n_6), .in1 (in1[3]), .out (n_8));
  nor2$ g4236(.in0 (in1[7]), .in1 (in1[6]), .out (n_7));
  inv1$ g4240(.in (in1[4]), .out (n_10));
  inv1$ g4245(.in (in2[3]), .out (n_6));
  inv1$ g4242(.in (in2[7]), .out (n_5));
  inv1$ g4247(.in (in1[3]), .out (n_4));
  inv1$ g4239(.in (in1[6]), .out (n_14));
  inv1$ g4237(.in (in1[5]), .out (n_16));
  inv1$ g4243(.in (in1[2]), .out (n_3));
  inv1$ g4244(.in (in1[7]), .out (n_2));
  inv1$ g4241(.in (in2[2]), .out (n_1));
  inv1$ g4246(.in (in2[0]), .out (n_0));
  inv1$ g4238(.in (in2[1]), .out (n_22));
endmodule

